schema_version = "1.0"

id = "lightforge"
version = "1.4.22"
name = "LightForge"
tagline = "Professional Studio Lighting System"
maintainer = "Cheluva <rayacheluva@gmail.com>"
type = "add-on"
website = "https://github.com/JohnCheluva/LightForge"
tags = ["lighting", "rendering", "3d"]

[blender]
min_version = "4.2.0"

[permissions]
network = { reason = "Check for updates (optional)" }
files = { reason = "Load custom textures and HDRIs" }
clipboard = { reason = "Copy/Paste settings" }
